[package]
name = "zip-unzip_ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.6.6"
gtk = "0.18.1"
url = "2.5.0"